import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'

const REPO = 'https://github.com/a1600778959/H743_FreeRTOS'

export default withMermaid({
  lang: 'zh-CN',
  title: 'Dima H743 Rover Wiki',
  description: 'Dima H743 FreeRTOS 差速车固件技术文档',
  ignoreDeadLinks: true,
  appearance: 'dark',
  head: [
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap' }],
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/logo.svg' }],
  ],
  markdown: { lineNumbers: true },
  outline: { level: [2, 3] },
  vite: { optimizeDeps: { include: ['mermaid'] } },
  mermaid: {
    theme: 'dark',
    themeVariables: {
      darkMode: true,
      background: '#0d1117',
      primaryColor: '#2d333b',
      primaryTextColor: '#e6edf3',
      primaryBorderColor: '#6d5dfc',
      secondaryColor: '#1c2333',
      secondaryTextColor: '#e6edf3',
      secondaryBorderColor: '#6d5dfc',
      tertiaryColor: '#161b22',
      tertiaryTextColor: '#e6edf3',
      tertiaryBorderColor: '#30363d',
      lineColor: '#8b949e',
      textColor: '#e6edf3',
      mainBkg: '#2d333b',
      nodeBkg: '#2d333b',
      nodeBorder: '#6d5dfc',
      nodeTextColor: '#e6edf3',
      clusterBkg: '#161b22',
      clusterBorder: '#30363d',
      titleColor: '#e6edf3',
      edgeLabelBackground: '#1c2333',
      actorBkg: '#2d333b',
      actorTextColor: '#e6edf3',
      actorBorder: '#6d5dfc',
      actorLineColor: '#8b949e',
      signalColor: '#e6edf3',
      signalTextColor: '#e6edf3',
      labelBoxBkgColor: '#2d333b',
      labelBoxBorderColor: '#6d5dfc',
      labelTextColor: '#e6edf3',
      loopTextColor: '#e6edf3',
      activationBorderColor: '#6d5dfc',
      activationBkgColor: '#1c2333',
      sequenceNumberColor: '#e6edf3',
      noteBkgColor: '#2d333b',
      noteTextColor: '#e6edf3',
      noteBorderColor: '#6d5dfc',
      classText: '#e6edf3',
      labelColor: '#e6edf3',
      altBackground: '#161b22',
    },
  },
  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'Dima H743 Rover Wiki',
    nav: [
      { text: '仓库', link: REPO },
      { text: '开始', link: '/01-getting-started/overview' },
    ],
    socialLinks: [{ icon: 'github', link: REPO }],
    outline: { label: '本页目录', level: [2, 3] },
    docFooter: { prev: '上一页', next: '下一页' },
    sidebar: [
      {
        text: 'Onboarding 使用指南',
        collapsed: false,
        items: [
          { text: '指南选择', link: '/onboarding/' },
          { text: '贡献者指南', link: '/onboarding/contributor-guide' },
          { text: '资深工程师指南', link: '/onboarding/staff-engineer-guide' },
          { text: '管理层指南', link: '/onboarding/executive-guide' },
          { text: '产品经理指南', link: '/onboarding/product-manager-guide' },
        ],
      },
      {
        text: '01 快速上手',
        collapsed: false,
        items: [
          { text: '项目总览', link: '/01-getting-started/overview' },
          { text: '构建与验证', link: '/01-getting-started/build-and-verify' },
          { text: '快速参考', link: '/01-getting-started/quick-reference' },
        ],
      },
      {
        text: '02 架构',
        collapsed: false,
        items: [
          { text: '分层架构与依赖规则', link: '/02-architecture/layered-architecture' },
          { text: '话题与数据流', link: '/02-architecture/data-flow' },
          { text: '线程与调度', link: '/02-architecture/threading-scheduling' },
          { text: '资源预算', link: '/02-architecture/resource-budget' },
        ],
      },
      {
        text: '03 Rover 控制域',
        collapsed: false,
        items: [
          { text: '差速控制栈', link: '/03-rover-domain/control-stack' },
          { text: '差速驱动与控制环', link: '/03-rover-domain/differential-drive' },
          { text: '手动模式语义', link: '/03-rover-domain/manual-mode' },
          { text: 'AutoMode 航段任务', link: '/03-rover-domain/auto-mode' },
          { text: '制动接管', link: '/03-rover-domain/braking-takeover' },
        ],
      },
      {
        text: '04 自动校准',
        collapsed: false,
        items: [
          { text: '状态机与调度合同', link: '/04-auto-calibration/state-machine' },
          { text: '会话生命周期', link: '/04-auto-calibration/session-lifecycle' },
          { text: '激励与剖面观测', link: '/04-auto-calibration/excitation-profiling' },
          { text: '辨识与 PI 公式', link: '/04-auto-calibration/identification-pi' },
          { text: '磁校准与磁油门补偿', link: '/04-auto-calibration/magnetic-calibration' },
          { text: 'RTK 与校准导航', link: '/04-auto-calibration/rtk-navigation' },
          { text: '事务与组调度', link: '/04-auto-calibration/transactions-groups' },
          { text: '收尾与失败分类', link: '/04-auto-calibration/finalize-failures' },
          { text: '阶段深读：Rtk.cpp', link: '/04-auto-calibration/stage-rtk' },
          { text: '阶段深读：Tuning.cpp', link: '/04-auto-calibration/stage-tuning' },
          { text: '阶段深读：RuntimeParameters.cpp', link: '/04-auto-calibration/stage-runtime-params' },
          { text: '阶段深读：GainParameters.cpp', link: '/04-auto-calibration/stage-gain-params' },
        ],
      },
      {
        text: '05 运行模块',
        collapsed: true,
        items: [
          { text: '模块全景', link: '/05-modules/modules' },
          { text: 'MotorOutput 输出链', link: '/05-modules/motor-output' },
          { text: 'Commander 安全链', link: '/05-modules/commander' },
          { text: 'MAVLink 链路', link: '/05-modules/mavlink' },
          { text: '日志系统', link: '/05-modules/logging' },
          { text: 'BootHealth 喂狗策略', link: '/05-modules/boot-health' },
          { text: 'EKF2 输入', link: '/05-modules/ekf2' },
          { text: '传感器校准', link: '/05-modules/sensor-calibration' },
        ],
      },
      {
        text: '06 中间件',
        collapsed: true,
        items: [
          { text: '参数 / uORB / 存储域', link: '/06-middleware/middleware' },
          { text: '参数系统', link: '/06-middleware/parameter-system' },
          { text: '存储域', link: '/06-middleware/storage-domains' },
          { text: 'QGC 兼容契约', link: '/06-middleware/qgc-compat' },
          { text: '事件系统与性能计数器', link: '/06-middleware/events-perf' },
        ],
      },
      {
        text: '07 平台层',
        collapsed: true,
        items: [
          { text: 'Capability 契约与组合根', link: '/07-platform/platform' },
          { text: 'ArmedFlash 协调器', link: '/07-platform/armed-flash' },
          { text: 'USB Console', link: '/07-platform/usb-console' },
        ],
      },
      {
        text: '08 驱动',
        collapsed: true,
        items: [
          { text: 'UM982 与 DroneCAN 链路', link: '/08-drivers/drivers' },
          { text: 'UM982 链路', link: '/08-drivers/um982' },
          { text: 'DroneCAN 链路', link: '/08-drivers/dronecan' },
        ],
      },
      {
        text: '09 构建与发布',
        collapsed: true,
        items: [
          { text: '构建、签名与 OTA', link: '/09-build-release/build-release' },
          { text: 'MCUboot 与恢复', link: '/09-build-release/mcuboot-recovery' },
        ],
      },
      {
        text: '10 工具链',
        collapsed: true,
        items: [
          { text: '架构门禁与验证工具', link: '/10-tooling/tooling' },
          { text: '生成链与会话工具', link: '/10-tooling/generator-chain' },
        ],
      },
      {
        text: '11 首次运行与参数标准',
        collapsed: false,
        items: [
          { text: '首次运行总流程', link: '/11-first-run/first-run-flow' },
          { text: '参数基线与三类必设', link: '/11-first-run/param-classes' },
          { text: '分阶段验收标准', link: '/11-first-run/stage-standard' },
          { text: '自动校准现场指南', link: '/11-first-run/autocal-field-guide' },
          { text: '现场速查与清单', link: '/11-first-run/field-checklists' },
        ],
      },
      {
        text: '12 启动与板级',
        collapsed: true,
        items: [
          { text: '启动链', link: '/12-startup-board/startup-chain' },
          { text: '板级层', link: '/12-startup-board/boards-h743' },
          { text: 'CubeMX 生成层', link: '/12-startup-board/core-hal' },
        ],
      },
      {
        text: '13 驱动与外设',
        collapsed: true,
        items: [
          { text: '驱动全量清单', link: '/13-drivers-peripherals/drivers-inventory' },
          { text: '串口与 RC 模块', link: '/13-drivers-peripherals/serial-rc' },
          { text: 'Mission 任务模块', link: '/13-drivers-peripherals/mission' },
        ],
      },
      {
        text: '14 平台内幕',
        collapsed: true,
        items: [
          { text: 'FreeRTOS 平台内幕', link: '/14-platform-internals/freertos-internals' },
          { text: 'STM32H7 后端', link: '/14-platform-internals/stm32h7-backends' },
        ],
      },
      {
        text: '15 MAVLink 运行配置',
        collapsed: true,
        items: [
          { text: 'MAVLink 运行配置', link: '/15-mavlink-runtime/mavlink-runtime' },
        ],
      },
      {
        text: '16 支撑库',
        collapsed: true,
        items: [
          { text: '支撑库', link: '/16-support-libs/support-libs' },
        ],
      },
      {
        text: '17 文档地图',
        collapsed: true,
        items: [
          { text: '权威文档导读', link: '/17-docs-map/docs-map' },
          { text: 'ADR 索引', link: '/17-docs-map/adr-index' },
        ],
      },
    ],
  },
})
